services:
  - type: web
    name: embedding-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PORT
        value: 8000
      - key: MODEL_CACHE_DIR
        value: /app/model_cache